-- WARNING: This schema is for reference only.
-- Table order and constraints may not be valid for execution order.

CREATE TABLE public.account_balances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  account_id uuid,
  fiscal_year_id uuid,
  period text,
  opening_balance numeric DEFAULT 0,
  debit_total numeric DEFAULT 0,
  credit_total numeric DEFAULT 0,
  closing_balance numeric DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT account_balances_pkey PRIMARY KEY (id),
  CONSTRAINT account_balances_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT account_balances_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT account_balances_fiscal_year_id_fkey FOREIGN KEY (fiscal_year_id) REFERENCES public.fiscal_years(id)
);
CREATE TABLE public.account_types (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  name_ar text,
  normal_balance text CHECK (normal_balance = ANY (ARRAY['debit'::text, 'credit'::text])),
  report_type text CHECK (report_type = ANY (ARRAY['bs'::text, 'pl'::text, 'cf'::text])),
  description text,
  CONSTRAINT account_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  code text NOT NULL,
  name text NOT NULL,
  name_en text,
  type_id uuid,
  parent_id uuid,
  level integer DEFAULT 1,
  is_header boolean DEFAULT false,
  allow_reconciliation boolean DEFAULT false,
  currency_code text,
  current_balance numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT accounts_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.account_types(id),
  CONSTRAINT accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.accounts(id),
  CONSTRAINT accounts_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(code)
);
CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  details jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  code text,
  address text,
  is_main boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid,
  name text NOT NULL,
  name_en text,
  email text,
  phone text,
  address text,
  tax_number text,
  commercial_register text,
  logo_url text,
  base_currency_code text,
  settings jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT companies_base_currency_code_fkey FOREIGN KEY (base_currency_code) REFERENCES public.currencies(code)
);
CREATE TABLE public.cost_centers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  code text,
  parent_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT cost_centers_pkey PRIMARY KEY (id),
  CONSTRAINT cost_centers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT cost_centers_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.cost_centers(id)
);
CREATE TABLE public.currencies (
  code text NOT NULL,
  name text NOT NULL,
  name_ar text,
  symbol text,
  exchange_rate numeric DEFAULT 1.0,
  is_base boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT currencies_pkey PRIMARY KEY (code)
);
CREATE TABLE public.document_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid,
  product_id uuid,
  variant_id uuid,
  description text,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  unit_cost numeric,
  tax_id uuid,
  tax_rate numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total numeric NOT NULL,
  warehouse_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT document_items_pkey PRIMARY KEY (id),
  CONSTRAINT document_items_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT document_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id),
  CONSTRAINT document_items_tax_id_fkey FOREIGN KEY (tax_id) REFERENCES public.tax_codes(id),
  CONSTRAINT document_items_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id)
);
CREATE TABLE public.document_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid,
  voucher_id uuid,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT document_payments_pkey PRIMARY KEY (id),
  CONSTRAINT document_payments_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_payments_voucher_id_fkey FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id)
);
CREATE TABLE public.document_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  type text CHECK (type = ANY (ARRAY['invoice'::text, 'quotation'::text, 'receipt'::text, 'po'::text])),
  content_html text,
  styles_css text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT document_templates_pkey PRIMARY KEY (id),
  CONSTRAINT document_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  type text CHECK (type = ANY (ARRAY['invoice'::text, 'bill'::text, 'quote'::text, 'order'::text, 'return'::text, 'credit_note'::text, 'debit_note'::text])),
  document_number text NOT NULL,
  date date DEFAULT CURRENT_DATE,
  due_date date,
  partner_id uuid,
  warehouse_id uuid,
  currency_code text,
  exchange_rate numeric DEFAULT 1.0,
  subtotal numeric DEFAULT 0,
  tax_total numeric DEFAULT 0,
  discount_total numeric DEFAULT 0,
  shipping_cost numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  paid_amount numeric DEFAULT 0,
  remaining_amount numeric DEFAULT (total_amount - paid_amount),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending'::text, 'approved'::text, 'paid'::text, 'void'::text, 'cancelled'::text])),
  notes text,
  terms_conditions text,
  generated_entry_id uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT documents_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT documents_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT documents_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(code),
  CONSTRAINT documents_generated_entry_id_fkey FOREIGN KEY (generated_entry_id) REFERENCES public.journal_entries(id)
);
CREATE TABLE public.exchange_rates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  from_currency text,
  to_currency text,
  rate numeric NOT NULL,
  effective_date timestamp with time zone DEFAULT now(),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (id),
  CONSTRAINT exchange_rates_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT exchange_rates_from_currency_fkey FOREIGN KEY (from_currency) REFERENCES public.currencies(code),
  CONSTRAINT exchange_rates_to_currency_fkey FOREIGN KEY (to_currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.fiscal_years (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text])),
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT fiscal_years_pkey PRIMARY KEY (id),
  CONSTRAINT fiscal_years_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  warehouse_id uuid,
  location_id uuid,
  product_id uuid,
  variant_id uuid,
  transaction_type text CHECK (transaction_type = ANY (ARRAY['in'::text, 'out'::text, 'transfer'::text, 'adjustment'::text, 'count'::text, 'production'::text])),
  quantity numeric NOT NULL CHECK (quantity >= 0::numeric),
  unit_cost numeric,
  total_cost numeric,
  reference_type text,
  reference_id uuid,
  balance_before numeric,
  balance_after numeric,
  expiry_date date,
  batch_number text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT inventory_transactions_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT inventory_transactions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.storage_locations(id),
  CONSTRAINT inventory_transactions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_transactions_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.journal_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  branch_id uuid,
  fiscal_year_id uuid,
  entry_number text NOT NULL,
  entry_date date DEFAULT CURRENT_DATE,
  description text,
  reference_type text,
  reference_id uuid,
  total_debit numeric DEFAULT 0,
  total_credit numeric DEFAULT 0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'posted'::text, 'reversed'::text, 'cancelled'::text])),
  posted_at timestamp with time zone,
  posted_by uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entries_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT journal_entries_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT journal_entries_fiscal_year_id_fkey FOREIGN KEY (fiscal_year_id) REFERENCES public.fiscal_years(id)
);
CREATE TABLE public.journal_entry_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  journal_entry_id uuid,
  company_id uuid,
  account_id uuid,
  description text,
  debit numeric DEFAULT 0 CHECK (debit >= 0::numeric),
  credit numeric DEFAULT 0 CHECK (credit >= 0::numeric),
  currency_code text,
  exchange_rate numeric DEFAULT 1.0,
  cost_center_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT journal_entry_lines_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entry_lines_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT journal_entry_lines_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT journal_entry_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT journal_entry_lines_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(code),
  CONSTRAINT journal_entry_lines_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES public.cost_centers(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  company_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text DEFAULT 'info'::text,
  is_read boolean DEFAULT false,
  link text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  type text CHECK (type = ANY (ARRAY['customer'::text, 'supplier'::text, 'both'::text])),
  name text NOT NULL,
  code text,
  contact_person text,
  phone text,
  email text,
  website text,
  tax_number text,
  address text,
  city text,
  country text,
  currency_code text,
  credit_limit numeric,
  payment_terms_days integer DEFAULT 0,
  opening_balance numeric DEFAULT 0,
  current_balance numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT partners_pkey PRIMARY KEY (id),
  CONSTRAINT partners_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT partners_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(code)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  name_en text,
  type text CHECK (type = ANY (ARRAY['cash'::text, 'bank'::text, 'card'::text, 'check'::text, 'other'::text])),
  details jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payment_methods_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.product_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  parent_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT product_categories_pkey PRIMARY KEY (id),
  CONSTRAINT product_categories_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT product_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.product_categories(id)
);
CREATE TABLE public.product_variants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid,
  sku text,
  name text,
  price_adjustment numeric DEFAULT 0,
  attributes jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  name_en text,
  sku text,
  barcode text,
  item_number text,
  manufacturer_code text,
  reorder_quantity numeric DEFAULT 0,
  category text,
  category_id uuid,
  unit text,
  unit_id uuid,
  cost numeric DEFAULT 0,
  price numeric DEFAULT 0,
  quantity numeric DEFAULT 0,
  min_quantity numeric DEFAULT 0,
  description text,
  manufacturer text,
  track_stock boolean DEFAULT true,
  allow_negative_stock boolean DEFAULT false,
  image_url text,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id),
  CONSTRAINT products_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  auth_user_id uuid,
  email text NOT NULL UNIQUE,
  full_name text,
  phone text,
  avatar_url text,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  query text,
  config jsonb,
  is_public boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  name_ar text,
  description text,
  permissions jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT roles_pkey PRIMARY KEY (id),
  CONSTRAINT roles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.storage_locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  warehouse_id uuid,
  name text NOT NULL,
  code text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT storage_locations_pkey PRIMARY KEY (id),
  CONSTRAINT storage_locations_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id)
);
CREATE TABLE public.tax_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  code text,
  rate numeric NOT NULL DEFAULT 0,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT tax_codes_pkey PRIMARY KEY (id),
  CONSTRAINT tax_codes_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  subscription_plan text DEFAULT 'free'::text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transfer_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transfer_order_id uuid,
  product_id uuid,
  quantity numeric NOT NULL,
  received_quantity numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT transfer_items_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_items_transfer_order_id_fkey FOREIGN KEY (transfer_order_id) REFERENCES public.transfer_orders(id),
  CONSTRAINT transfer_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.transfer_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  order_number text NOT NULL,
  from_warehouse_id uuid,
  to_warehouse_id uuid,
  date date DEFAULT CURRENT_DATE,
  status text CHECK (status = ANY (ARRAY['draft'::text, 'pending'::text, 'approved'::text, 'shipped'::text, 'received'::text, 'cancelled'::text])),
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT transfer_orders_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT transfer_orders_from_warehouse_id_fkey FOREIGN KEY (from_warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT transfer_orders_to_warehouse_id_fkey FOREIGN KEY (to_warehouse_id) REFERENCES public.warehouses(id)
);
CREATE TABLE public.units (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  name_en text,
  code text,
  conversion_factor numeric DEFAULT 1,
  base_unit_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT units_pkey PRIMARY KEY (id),
  CONSTRAINT units_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT units_base_unit_id_fkey FOREIGN KEY (base_unit_id) REFERENCES public.units(id)
);
CREATE TABLE public.user_companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  company_id uuid,
  role_id uuid,
  is_owner boolean DEFAULT false,
  is_default boolean DEFAULT false,
  appointed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT user_companies_pkey PRIMARY KEY (id),
  CONSTRAINT user_companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT user_companies_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.vouchers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  voucher_number text NOT NULL,
  type text CHECK (type = ANY (ARRAY['receipt'::text, 'payment'::text])),
  partner_id uuid,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency_code text,
  exchange_rate numeric DEFAULT 1.0,
  payment_method_id uuid,
  date date DEFAULT CURRENT_DATE,
  description text,
  reference_number text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'posted'::text, 'void'::text])),
  journal_entry_id uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  posted_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT vouchers_pkey PRIMARY KEY (id),
  CONSTRAINT vouchers_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id),
  CONSTRAINT vouchers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT vouchers_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT vouchers_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(code),
  CONSTRAINT vouchers_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE TABLE public.warehouses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  address text,
  manager_id uuid,
  is_main boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT warehouses_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
